CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, description text, is_super_admin boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS role_permissions (role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS admins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), google_id text UNIQUE, email text UNIQUE NOT NULL, name text, avatar_url text, role_id uuid NOT NULL REFERENCES roles(id), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), last_login_at timestamptz);
CREATE TABLE IF NOT EXISTS admin_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), admin_id uuid NOT NULL REFERENCES admins(id) ON DELETE CASCADE, token_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS gallery_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, description text, type text NOT NULL CHECK (type IN ('IMAGE','VIDEO')), cloudinary_public_id text NOT NULL UNIQUE, cloudinary_resource_type text NOT NULL, cloudinary_url text NOT NULL, width integer, height integer, duration numeric, format text, bytes integer, alt_text text, sort_order integer NOT NULL DEFAULT 0, is_published boolean NOT NULL DEFAULT false, created_by uuid REFERENCES admins(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS site_settings (key text PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_admins_active ON admins(is_active); CREATE INDEX IF NOT EXISTS idx_gallery_published_sort ON gallery_items(is_published, sort_order, created_at DESC); CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);
INSERT INTO permissions(name, description) VALUES
('GALLERY_VIEW','View gallery admin'),('GALLERY_UPLOAD','Upload gallery media'),('GALLERY_EDIT','Edit gallery media'),('GALLERY_DELETE','Delete gallery media'),('SETTINGS_VIEW','View settings'),('SETTINGS_EDIT','Edit settings'),('ADMINS_VIEW','View administrators'),('ADMINS_INVITE','Add administrators'),('ADMINS_REVOKE','Revoke administrators'),('ADMINS_EDIT','Edit administrators'),('ROLES_VIEW','View roles'),('ROLES_CREATE','Create roles'),('ROLES_EDIT','Edit roles'),('ROLES_DELETE','Delete roles') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles(name, description, is_super_admin) VALUES ('SUPER_ADMIN','Full administrative access', true),('ADMIN','General administrator', false),('EDITOR','Gallery content editor', false) ON CONFLICT (name) DO NOTHING;
INSERT INTO role_permissions(role_id, permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='SUPER_ADMIN' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.name IN ('GALLERY_VIEW','GALLERY_UPLOAD','GALLERY_EDIT','SETTINGS_VIEW','ADMINS_VIEW','ROLES_VIEW') WHERE r.name='ADMIN' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.name IN ('GALLERY_VIEW','GALLERY_UPLOAD','GALLERY_EDIT') WHERE r.name='EDITOR' ON CONFLICT DO NOTHING;
INSERT INTO site_settings(key,value) VALUES ('general','{"companyName":"GGP Images","companyDescription":"Premium printing and branding solutions that make your business unforgettable.","phone":"+233548844321","email":"hello@ggpimages.com","address":"ZEN Filling Station via Apremdo New Market, off Apollo, Anaji Rd, Takoradi"}'::jsonb) ON CONFLICT (key) DO NOTHING;
